/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.artistry2;

import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Collection;
import java.util.TreeMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JRadioButton;

/**
 *
 * @author advikarapolu
 */
public class MainWindow extends javax.swing.JFrame {
    
    private int checkBoxesFilled;
    private UserSelection userSelection;
    private DataHandler dh;
    private ArrayList<JCheckBox> checkboxes;
    private ArrayList<BufferedImage> imagePanels;
    private ArrayList<BufferedImage> individualPanels;
    private int countClicks;
    private ArrayList<String> imageLabels;
    private ArrayList<JButton> mainButtons;
    private  ArrayList<Artwork> artworks;
    private QuizEvaluator qe;

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        
        checkBoxesFilled = 0;
        userSelection = new UserSelection();
        dh = new DataHandler();
        checkboxes = new ArrayList<>();
        imagePanels = new ArrayList<>();
        individualPanels = new ArrayList<>();
        countClicks = 0;
        imageLabels = new ArrayList<>();
        mainButtons = new ArrayList<>();
        artworks = new ArrayList<>();
        qe = new QuizEvaluator(artworks);
       
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_base = new javax.swing.JPanel();
        panel_welcome = new javax.swing.JPanel();
        label_Welcome = new javax.swing.JLabel();
        panel_options = new javax.swing.JPanel();
        label_AncientGreece = new javax.swing.JLabel();
        label_Asia = new javax.swing.JLabel();
        label_Africa = new javax.swing.JLabel();
        label_Americas = new javax.swing.JLabel();
        label_Animals = new javax.swing.JLabel();
        label_Architecture = new javax.swing.JLabel();
        label_Modernism = new javax.swing.JLabel();
        label_Pop = new javax.swing.JLabel();
        label_Landscapes = new javax.swing.JLabel();
        label_Impressionism = new javax.swing.JLabel();
        label_Photography = new javax.swing.JLabel();
        label_Miniature = new javax.swing.JLabel();
        checkBox_AncientGreece = new javax.swing.JCheckBox();
        checkBox_Americas = new javax.swing.JCheckBox();
        checkBox_Modernism = new javax.swing.JCheckBox();
        checkBox_Impressionism = new javax.swing.JCheckBox();
        checkBox_Asia = new javax.swing.JCheckBox();
        checkBox_Animals = new javax.swing.JCheckBox();
        checkBox_Pop = new javax.swing.JCheckBox();
        checkBox_Photography = new javax.swing.JCheckBox();
        checkBox_Africa = new javax.swing.JCheckBox();
        checkBox_Architecture = new javax.swing.JCheckBox();
        checkBox_Landscapes = new javax.swing.JCheckBox();
        checkBox_Miniature = new javax.swing.JCheckBox();
        button_Proceed = new javax.swing.JButton();
        label_counter = new javax.swing.JLabel();
        panel_mainScreen = new javax.swing.JPanel();
        label_MainScreen = new javax.swing.JLabel();
        button_Instructions = new javax.swing.JButton();
        button_regenerate = new javax.swing.JButton();
        button_miniQuiz = new javax.swing.JButton();
        panel_Images = new javax.swing.JPanel();
        panel_ImageView1 = new ImagePanel();
        button_XImage1 = new javax.swing.JButton();
        button_MaxImage1 = new javax.swing.JButton();
        panel_ImageView2 = new ImagePanel();
        button_XImage2 = new javax.swing.JButton();
        button_MaxImage2 = new javax.swing.JButton();
        panel_ImageView3 = new ImagePanel();
        button_XImage3 = new javax.swing.JButton();
        button_MaxImage3 = new javax.swing.JButton();
        label_LabelView2 = new javax.swing.JLabel();
        label_LabelView1 = new javax.swing.JLabel();
        label_LabelView3 = new javax.swing.JLabel();
        button_Next = new javax.swing.JButton();
        button_Back = new javax.swing.JButton();
        panel_Instructions = new javax.swing.JPanel();
        label_Instructions = new javax.swing.JLabel();
        button_backToMain = new javax.swing.JButton();
        scrollPane_instructions = new javax.swing.JScrollPane();
        textArea_instructions = new javax.swing.JTextArea();
        panel_quiz = new javax.swing.JPanel();
        label_MiniQuiz = new javax.swing.JLabel();
        button_backToMain1 = new javax.swing.JButton();
        panel_quizScreen = new javax.swing.JPanel();
        panel_question1 = new javax.swing.JPanel();
        label_question1 = new javax.swing.JLabel();
        radioButton_answer3 = new javax.swing.JRadioButton();
        radioButton_answer1 = new javax.swing.JRadioButton();
        radioButton_answer2 = new javax.swing.JRadioButton();
        radioButton_answer4 = new javax.swing.JRadioButton();
        radioButton_answer5 = new javax.swing.JRadioButton();
        panel_question2 = new javax.swing.JPanel();
        label_question2 = new javax.swing.JLabel();
        panel_individualScreen = new javax.swing.JPanel();
        button_backToMain2 = new javax.swing.JButton();
        panel_individualDeets = new javax.swing.JPanel();
        panel_individualImage = new ImagePanel();
        comboBox_shareOptions = new javax.swing.JComboBox<>();
        panel_pieceDeets = new javax.swing.JPanel();
        label_Title = new javax.swing.JLabel();
        label_Date = new javax.swing.JLabel();
        label_Artist = new javax.swing.JLabel();
        label_Place = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        textPane_description = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        panel_base.setBackground(new java.awt.Color(212, 189, 163));
        panel_base.setLayout(new java.awt.CardLayout());

        panel_welcome.setBackground(new java.awt.Color(212, 189, 163));

        label_Welcome.setBackground(new java.awt.Color(205, 110, 110));
        label_Welcome.setFont(new java.awt.Font("Cochin", 1, 16)); // NOI18N
        label_Welcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_Welcome.setText("Welcome to Artistry, an art history app to expand your cultural knowledge! Select up to five locations, cultures, mediums, and time periods to get started.");
        label_Welcome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        label_Welcome.setOpaque(true);

        panel_options.setBackground(new java.awt.Color(212, 189, 163));
        panel_options.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_AncientGreece.setFont(new java.awt.Font("Cochin", 0, 14)); // NOI18N
        label_AncientGreece.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_AncientGreece.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ancient_Greece_2.jpeg"))); // NOI18N
        label_AncientGreece.setText("Greece, Rome, and Byzantium");
        label_AncientGreece.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        label_AncientGreece.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        panel_options.add(label_AncientGreece, new org.netbeans.lib.awtextra.AbsoluteConstraints(-120, 0, 522, 174));

        label_Asia.setFont(new java.awt.Font("Cochin", 0, 14)); // NOI18N
        label_Asia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_Asia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Asia.jpg"))); // NOI18N
        label_Asia.setText("Asia");
        label_Asia.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        label_Asia.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        panel_options.add(label_Asia, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 522, 174));

        label_Africa.setFont(new java.awt.Font("Cochin", 0, 14)); // NOI18N
        label_Africa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_Africa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Africa.jpg"))); // NOI18N
        label_Africa.setText("Africa");
        label_Africa.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        label_Africa.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        panel_options.add(label_Africa, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 0, 522, 174));

        label_Americas.setFont(new java.awt.Font("Cochin", 0, 14)); // NOI18N
        label_Americas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_Americas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Americas.jpg"))); // NOI18N
        label_Americas.setText("Americas");
        label_Americas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        label_Americas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        panel_options.add(label_Americas, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 0, 522, 174));

        label_Animals.setFont(new java.awt.Font("Cochin", 0, 14)); // NOI18N
        label_Animals.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_Animals.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Animals.jpg"))); // NOI18N
        label_Animals.setText("Animals");
        label_Animals.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        label_Animals.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        panel_options.add(label_Animals, new org.netbeans.lib.awtextra.AbsoluteConstraints(-120, 190, 522, 174));

        label_Architecture.setFont(new java.awt.Font("Cochin", 0, 14)); // NOI18N
        label_Architecture.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_Architecture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Architecture.jpg"))); // NOI18N
        label_Architecture.setText("Architecture");
        label_Architecture.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        label_Architecture.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        panel_options.add(label_Architecture, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 522, 174));

        label_Modernism.setFont(new java.awt.Font("Cochin", 0, 14)); // NOI18N
        label_Modernism.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_Modernism.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Modernism.jpg"))); // NOI18N
        label_Modernism.setText("Modernism");
        label_Modernism.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        label_Modernism.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        panel_options.add(label_Modernism, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 190, 522, 174));

        label_Pop.setFont(new java.awt.Font("Cochin", 0, 14)); // NOI18N
        label_Pop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_Pop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pop.jpg"))); // NOI18N
        label_Pop.setText("Pop");
        label_Pop.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        label_Pop.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        panel_options.add(label_Pop, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 190, 522, 174));

        label_Landscapes.setFont(new java.awt.Font("Cochin", 0, 14)); // NOI18N
        label_Landscapes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_Landscapes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Landscape.jpeg"))); // NOI18N
        label_Landscapes.setText("Landscapes");
        label_Landscapes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        label_Landscapes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        panel_options.add(label_Landscapes, new org.netbeans.lib.awtextra.AbsoluteConstraints(-120, 380, 522, 174));

        label_Impressionism.setFont(new java.awt.Font("Cochin", 0, 14)); // NOI18N
        label_Impressionism.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_Impressionism.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Impressionism.jpg"))); // NOI18N
        label_Impressionism.setText("Impressionism");
        label_Impressionism.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        label_Impressionism.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        panel_options.add(label_Impressionism, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 380, 522, 174));

        label_Photography.setFont(new java.awt.Font("Cochin", 0, 14)); // NOI18N
        label_Photography.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_Photography.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photography.jpg"))); // NOI18N
        label_Photography.setText("Photography");
        label_Photography.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        label_Photography.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        panel_options.add(label_Photography, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 380, 522, 174));

        label_Miniature.setFont(new java.awt.Font("Cochin", 0, 14)); // NOI18N
        label_Miniature.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_Miniature.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Miniature.jpg"))); // NOI18N
        label_Miniature.setText("Miniature");
        label_Miniature.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        label_Miniature.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        panel_options.add(label_Miniature, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 380, 522, 174));

        checkBox_AncientGreece.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBox_AncientGreeceActionPerformed(evt);
            }
        });
        panel_options.add(checkBox_AncientGreece, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, -1, -1));

        checkBox_Americas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBox_AmericasActionPerformed(evt);
            }
        });
        panel_options.add(checkBox_Americas, new org.netbeans.lib.awtextra.AbsoluteConstraints(1340, 0, -1, -1));

        checkBox_Modernism.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBox_ModernismActionPerformed(evt);
            }
        });
        panel_options.add(checkBox_Modernism, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 190, -1, -1));

        checkBox_Impressionism.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBox_ImpressionismActionPerformed(evt);
            }
        });
        panel_options.add(checkBox_Impressionism, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 380, -1, -1));

        checkBox_Asia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBox_AsiaActionPerformed(evt);
            }
        });
        panel_options.add(checkBox_Asia, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 0, -1, -1));

        checkBox_Animals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBox_AnimalsActionPerformed(evt);
            }
        });
        panel_options.add(checkBox_Animals, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, -1, 20));

        checkBox_Pop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBox_PopActionPerformed(evt);
            }
        });
        panel_options.add(checkBox_Pop, new org.netbeans.lib.awtextra.AbsoluteConstraints(1340, 190, -1, -1));

        checkBox_Photography.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBox_PhotographyActionPerformed(evt);
            }
        });
        panel_options.add(checkBox_Photography, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 380, -1, -1));

        checkBox_Africa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBox_AfricaActionPerformed(evt);
            }
        });
        panel_options.add(checkBox_Africa, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 0, -1, -1));

        checkBox_Architecture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBox_ArchitectureActionPerformed(evt);
            }
        });
        panel_options.add(checkBox_Architecture, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 190, -1, -1));

        checkBox_Landscapes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBox_LandscapesActionPerformed(evt);
            }
        });
        panel_options.add(checkBox_Landscapes, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 380, -1, -1));

        checkBox_Miniature.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBox_MiniatureActionPerformed(evt);
            }
        });
        panel_options.add(checkBox_Miniature, new org.netbeans.lib.awtextra.AbsoluteConstraints(1340, 380, -1, -1));

        button_Proceed.setBackground(new java.awt.Color(250, 203, 132));
        button_Proceed.setFont(new java.awt.Font("Cochin", 1, 16)); // NOI18N
        button_Proceed.setText("Proceed to Curated Art Pieces!");
        button_Proceed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_ProceedActionPerformed(evt);
            }
        });
        panel_options.add(button_Proceed, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 620, 330, 50));

        label_counter.setBackground(new java.awt.Color(205, 110, 110));
        label_counter.setFont(new java.awt.Font("Cochin", 1, 14)); // NOI18N
        label_counter.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_counter.setText("You have selected 0 out of 5 available options.");
        label_counter.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        label_counter.setOpaque(true);
        panel_options.add(label_counter, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 570, 430, 40));

        javax.swing.GroupLayout panel_welcomeLayout = new javax.swing.GroupLayout(panel_welcome);
        panel_welcome.setLayout(panel_welcomeLayout);
        panel_welcomeLayout.setHorizontalGroup(
            panel_welcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_welcomeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_welcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_welcomeLayout.createSequentialGroup()
                        .addComponent(panel_options, javax.swing.GroupLayout.PREFERRED_SIZE, 1450, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(label_Welcome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panel_welcomeLayout.setVerticalGroup(
            panel_welcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_welcomeLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(label_Welcome, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panel_options, javax.swing.GroupLayout.DEFAULT_SIZE, 687, Short.MAX_VALUE)
                .addContainerGap())
        );

        panel_base.add(panel_welcome, "card2");

        panel_mainScreen.setBackground(new java.awt.Color(212, 189, 163));
        panel_mainScreen.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_MainScreen.setBackground(new java.awt.Color(205, 110, 110));
        label_MainScreen.setFont(new java.awt.Font("Cochin", 1, 18)); // NOI18N
        label_MainScreen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_MainScreen.setText("Explore your personal Artistry collection below!");
        label_MainScreen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        label_MainScreen.setOpaque(true);
        panel_mainScreen.add(label_MainScreen, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 14, 1457, 43));

        button_Instructions.setBackground(new java.awt.Color(205, 110, 110));
        button_Instructions.setFont(new java.awt.Font("Cochin", 1, 14)); // NOI18N
        button_Instructions.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Information_Icon.png"))); // NOI18N
        button_Instructions.setText("Instructions");
        button_Instructions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_InstructionsActionPerformed(evt);
            }
        });
        panel_mainScreen.add(button_Instructions, new org.netbeans.lib.awtextra.AbsoluteConstraints(1334, 63, -1, -1));

        button_regenerate.setBackground(new java.awt.Color(250, 203, 132));
        button_regenerate.setFont(new java.awt.Font("Cochin", 1, 18)); // NOI18N
        button_regenerate.setText("Regenerate all works");
        button_regenerate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_regenerateActionPerformed(evt);
            }
        });
        panel_mainScreen.add(button_regenerate, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 709, 207, 51));

        button_miniQuiz.setBackground(new java.awt.Color(250, 203, 132));
        button_miniQuiz.setFont(new java.awt.Font("Cochin", 1, 18)); // NOI18N
        button_miniQuiz.setText("Proceed to Mini Quiz");
        button_miniQuiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_miniQuizActionPerformed(evt);
            }
        });
        panel_mainScreen.add(button_miniQuiz, new org.netbeans.lib.awtextra.AbsoluteConstraints(1256, 709, 207, 51));

        panel_Images.setBackground(new java.awt.Color(212, 189, 163));

        panel_ImageView1.setBackground(new java.awt.Color(204, 204, 204));
        panel_ImageView1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        button_XImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/XButton.png"))); // NOI18N
        button_XImage1.setBorder(null);
        button_XImage1.setOpaque(true);

        button_MaxImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MaximizeButton.png"))); // NOI18N
        button_MaxImage1.setBorder(null);
        button_MaxImage1.setOpaque(true);
        button_MaxImage1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_MaxImage1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_ImageView1Layout = new javax.swing.GroupLayout(panel_ImageView1);
        panel_ImageView1.setLayout(panel_ImageView1Layout);
        panel_ImageView1Layout.setHorizontalGroup(
            panel_ImageView1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_ImageView1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(button_MaxImage1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(button_XImage1)
                .addContainerGap())
        );
        panel_ImageView1Layout.setVerticalGroup(
            panel_ImageView1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_ImageView1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_ImageView1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button_MaxImage1)
                    .addComponent(button_XImage1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panel_ImageView2.setBackground(new java.awt.Color(204, 204, 204));
        panel_ImageView2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        panel_ImageView2.setPreferredSize(new java.awt.Dimension(385, 462));

        button_XImage2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/XButton.png"))); // NOI18N
        button_XImage2.setBorder(null);
        button_XImage2.setOpaque(true);

        button_MaxImage2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MaximizeButton.png"))); // NOI18N
        button_MaxImage2.setBorder(null);
        button_MaxImage2.setOpaque(true);
        button_MaxImage2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_MaxImage2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_ImageView2Layout = new javax.swing.GroupLayout(panel_ImageView2);
        panel_ImageView2.setLayout(panel_ImageView2Layout);
        panel_ImageView2Layout.setHorizontalGroup(
            panel_ImageView2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_ImageView2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(button_MaxImage2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 276, Short.MAX_VALUE)
                .addComponent(button_XImage2)
                .addContainerGap())
        );
        panel_ImageView2Layout.setVerticalGroup(
            panel_ImageView2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_ImageView2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_ImageView2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button_MaxImage2)
                    .addComponent(button_XImage2))
                .addContainerGap(408, Short.MAX_VALUE))
        );

        panel_ImageView3.setBackground(new java.awt.Color(204, 204, 204));
        panel_ImageView3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        panel_ImageView3.setPreferredSize(new java.awt.Dimension(385, 462));

        button_XImage3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/XButton.png"))); // NOI18N
        button_XImage3.setBorder(null);
        button_XImage3.setOpaque(true);

        button_MaxImage3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MaximizeButton.png"))); // NOI18N
        button_MaxImage3.setBorder(null);
        button_MaxImage3.setOpaque(true);
        button_MaxImage3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_MaxImage3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_ImageView3Layout = new javax.swing.GroupLayout(panel_ImageView3);
        panel_ImageView3.setLayout(panel_ImageView3Layout);
        panel_ImageView3Layout.setHorizontalGroup(
            panel_ImageView3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_ImageView3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(button_MaxImage3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 276, Short.MAX_VALUE)
                .addComponent(button_XImage3)
                .addContainerGap())
        );
        panel_ImageView3Layout.setVerticalGroup(
            panel_ImageView3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_ImageView3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_ImageView3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button_MaxImage3)
                    .addComponent(button_XImage3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        label_LabelView2.setBackground(new java.awt.Color(99, 107, 47));
        label_LabelView2.setFont(new java.awt.Font("Cochin", 3, 14)); // NOI18N
        label_LabelView2.setForeground(new java.awt.Color(255, 255, 255));
        label_LabelView2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_LabelView2.setText("No Title");
        label_LabelView2.setOpaque(true);

        label_LabelView1.setBackground(new java.awt.Color(99, 107, 47));
        label_LabelView1.setFont(new java.awt.Font("Cochin", 3, 14)); // NOI18N
        label_LabelView1.setForeground(new java.awt.Color(255, 255, 255));
        label_LabelView1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_LabelView1.setText("No Title");
        label_LabelView1.setOpaque(true);

        label_LabelView3.setBackground(new java.awt.Color(99, 107, 47));
        label_LabelView3.setFont(new java.awt.Font("Cochin", 3, 14)); // NOI18N
        label_LabelView3.setForeground(new java.awt.Color(255, 255, 255));
        label_LabelView3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_LabelView3.setText("No Title");
        label_LabelView3.setOpaque(true);

        javax.swing.GroupLayout panel_ImagesLayout = new javax.swing.GroupLayout(panel_Images);
        panel_Images.setLayout(panel_ImagesLayout);
        panel_ImagesLayout.setHorizontalGroup(
            panel_ImagesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_ImagesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_ImagesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(label_LabelView1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .addComponent(panel_ImageView1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(panel_ImagesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panel_ImagesLayout.createSequentialGroup()
                        .addComponent(label_LabelView2, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(label_LabelView3, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_ImagesLayout.createSequentialGroup()
                        .addComponent(panel_ImageView2, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(panel_ImageView3, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
        );
        panel_ImagesLayout.setVerticalGroup(
            panel_ImagesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_ImagesLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(panel_ImagesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panel_ImageView1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel_ImageView2, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)
                    .addComponent(panel_ImageView3, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_ImagesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_LabelView2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_LabelView1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_LabelView3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        panel_mainScreen.add(panel_Images, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 1270, 560));

        button_Next.setFont(new java.awt.Font("Cochin", 1, 14)); // NOI18N
        button_Next.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NextButton.png"))); // NOI18N
        button_Next.setText("Next");
        button_Next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_NextActionPerformed(evt);
            }
        });
        panel_mainScreen.add(button_Next, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 340, -1, -1));

        button_Back.setFont(new java.awt.Font("Cochin", 1, 14)); // NOI18N
        button_Back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BackButton.png"))); // NOI18N
        button_Back.setText("Back");
        button_Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_BackActionPerformed(evt);
            }
        });
        panel_mainScreen.add(button_Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, -1, -1));

        panel_base.add(panel_mainScreen, "card3");

        panel_Instructions.setBackground(new java.awt.Color(212, 189, 163));

        label_Instructions.setBackground(new java.awt.Color(205, 110, 110));
        label_Instructions.setFont(new java.awt.Font("Cochin", 1, 16)); // NOI18N
        label_Instructions.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_Instructions.setText("Instructions");
        label_Instructions.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        label_Instructions.setOpaque(true);

        button_backToMain.setBackground(new java.awt.Color(141, 54, 54));
        button_backToMain.setFont(new java.awt.Font("Cochin", 1, 14)); // NOI18N
        button_backToMain.setForeground(new java.awt.Color(255, 255, 255));
        button_backToMain.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BackArrow.png"))); // NOI18N
        button_backToMain.setText("Back to Main Screen");
        button_backToMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_backToMainActionPerformed(evt);
            }
        });

        textArea_instructions.setEditable(false);
        textArea_instructions.setBackground(new java.awt.Color(141, 54, 54));
        textArea_instructions.setColumns(21);
        textArea_instructions.setFont(new java.awt.Font("Cochin", 1, 18)); // NOI18N
        textArea_instructions.setForeground(new java.awt.Color(255, 255, 255));
        textArea_instructions.setRows(5);
        textArea_instructions.setText("\t\t\n\t\n\n\n\t           \n       \t               You are currently viewing the 5 pieces selected from the options you selected. A quick overview of available options:\n\n\t\t\t        Click on the ‘X’ at the top-right corner of each work to replace it\n\n\t\t\t          Click ‘Regenerate all works’ to view a completely new selection\n\t\t\t\n\t\t                           Click ‘Proceed to mini-quiz’ to test your knowledge on the selected works\n\n\t\t                       Click the ‘maximize’ button at the top-left corner to view the artwork’s details");
        scrollPane_instructions.setViewportView(textArea_instructions);

        javax.swing.GroupLayout panel_InstructionsLayout = new javax.swing.GroupLayout(panel_Instructions);
        panel_Instructions.setLayout(panel_InstructionsLayout);
        panel_InstructionsLayout.setHorizontalGroup(
            panel_InstructionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_InstructionsLayout.createSequentialGroup()
                .addGroup(panel_InstructionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_InstructionsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panel_InstructionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_Instructions, javax.swing.GroupLayout.DEFAULT_SIZE, 1460, Short.MAX_VALUE)
                            .addGroup(panel_InstructionsLayout.createSequentialGroup()
                                .addComponent(button_backToMain)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(panel_InstructionsLayout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(scrollPane_instructions, javax.swing.GroupLayout.PREFERRED_SIZE, 1294, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panel_InstructionsLayout.setVerticalGroup(
            panel_InstructionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_InstructionsLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(label_Instructions, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(button_backToMain)
                .addGap(39, 39, 39)
                .addComponent(scrollPane_instructions, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(168, Short.MAX_VALUE))
        );

        panel_base.add(panel_Instructions, "card4");

        panel_quiz.setBackground(new java.awt.Color(212, 189, 163));

        label_MiniQuiz.setBackground(new java.awt.Color(205, 110, 110));
        label_MiniQuiz.setFont(new java.awt.Font("Cochin", 1, 16)); // NOI18N
        label_MiniQuiz.setForeground(new java.awt.Color(255, 255, 255));
        label_MiniQuiz.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_MiniQuiz.setText("Mini Quiz");
        label_MiniQuiz.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        label_MiniQuiz.setOpaque(true);

        button_backToMain1.setBackground(new java.awt.Color(99, 107, 47));
        button_backToMain1.setFont(new java.awt.Font("Cochin", 1, 14)); // NOI18N
        button_backToMain1.setForeground(new java.awt.Color(255, 255, 255));
        button_backToMain1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BackArrow.png"))); // NOI18N
        button_backToMain1.setText("Back to Main Screen");
        button_backToMain1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_backToMain1ActionPerformed(evt);
            }
        });

        panel_quizScreen.setLayout(new java.awt.CardLayout());

        panel_question1.setBackground(new java.awt.Color(99, 107, 47));
        panel_question1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        label_question1.setFont(new java.awt.Font("Cochin", 0, 24)); // NOI18N
        label_question1.setForeground(new java.awt.Color(255, 255, 255));
        label_question1.setText("When was the creation date of ");

        radioButton_answer3.setFont(new java.awt.Font("Cochin", 1, 16)); // NOI18N
        radioButton_answer3.setForeground(new java.awt.Color(255, 255, 255));
        radioButton_answer3.setText("jRadioButton1");

        radioButton_answer1.setFont(new java.awt.Font("Cochin", 1, 16)); // NOI18N
        radioButton_answer1.setForeground(new java.awt.Color(255, 255, 255));
        radioButton_answer1.setText("jRadioButton1");

        radioButton_answer2.setFont(new java.awt.Font("Cochin", 1, 16)); // NOI18N
        radioButton_answer2.setForeground(new java.awt.Color(255, 255, 255));
        radioButton_answer2.setText("jRadioButton1");
        radioButton_answer2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButton_answer2ActionPerformed(evt);
            }
        });

        radioButton_answer4.setFont(new java.awt.Font("Cochin", 1, 16)); // NOI18N
        radioButton_answer4.setForeground(new java.awt.Color(255, 255, 255));
        radioButton_answer4.setText("jRadioButton1");

        radioButton_answer5.setFont(new java.awt.Font("Cochin", 1, 16)); // NOI18N
        radioButton_answer5.setForeground(new java.awt.Color(255, 255, 255));
        radioButton_answer5.setText("jRadioButton1");

        javax.swing.GroupLayout panel_question1Layout = new javax.swing.GroupLayout(panel_question1);
        panel_question1.setLayout(panel_question1Layout);
        panel_question1Layout.setHorizontalGroup(
            panel_question1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_question1Layout.createSequentialGroup()
                .addGroup(panel_question1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_question1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(label_question1, javax.swing.GroupLayout.PREFERRED_SIZE, 1280, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_question1Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addGroup(panel_question1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(radioButton_answer2, javax.swing.GroupLayout.PREFERRED_SIZE, 1159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(radioButton_answer3, javax.swing.GroupLayout.PREFERRED_SIZE, 1159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(radioButton_answer4, javax.swing.GroupLayout.PREFERRED_SIZE, 1159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(radioButton_answer5, javax.swing.GroupLayout.PREFERRED_SIZE, 1159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panel_question1Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(radioButton_answer1, javax.swing.GroupLayout.PREFERRED_SIZE, 1159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        panel_question1Layout.setVerticalGroup(
            panel_question1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_question1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(label_question1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(radioButton_answer1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(radioButton_answer2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(radioButton_answer3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addComponent(radioButton_answer4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(radioButton_answer5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );

        panel_quizScreen.add(panel_question1, "card2");

        panel_question2.setBackground(new java.awt.Color(99, 107, 47));

        label_question2.setFont(new java.awt.Font("Cochin", 0, 24)); // NOI18N
        label_question2.setForeground(new java.awt.Color(255, 255, 255));
        label_question2.setText("Who was the creator of ");

        javax.swing.GroupLayout panel_question2Layout = new javax.swing.GroupLayout(panel_question2);
        panel_question2.setLayout(panel_question2Layout);
        panel_question2Layout.setHorizontalGroup(
            panel_question2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_question2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(label_question2, javax.swing.GroupLayout.PREFERRED_SIZE, 1280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );
        panel_question2Layout.setVerticalGroup(
            panel_question2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_question2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(label_question2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(472, Short.MAX_VALUE))
        );

        panel_quizScreen.add(panel_question2, "card3");

        javax.swing.GroupLayout panel_quizLayout = new javax.swing.GroupLayout(panel_quiz);
        panel_quiz.setLayout(panel_quizLayout);
        panel_quizLayout.setHorizontalGroup(
            panel_quizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_quizLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_quizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_MiniQuiz, javax.swing.GroupLayout.DEFAULT_SIZE, 1460, Short.MAX_VALUE)
                    .addGroup(panel_quizLayout.createSequentialGroup()
                        .addComponent(button_backToMain1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(panel_quizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_quizLayout.createSequentialGroup()
                    .addContainerGap(57, Short.MAX_VALUE)
                    .addComponent(panel_quizScreen, javax.swing.GroupLayout.PREFERRED_SIZE, 1366, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(49, Short.MAX_VALUE)))
        );
        panel_quizLayout.setVerticalGroup(
            panel_quizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_quizLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_MiniQuiz, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(button_backToMain1)
                .addContainerGap(679, Short.MAX_VALUE))
            .addGroup(panel_quizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_quizLayout.createSequentialGroup()
                    .addContainerGap(138, Short.MAX_VALUE)
                    .addComponent(panel_quizScreen, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(76, Short.MAX_VALUE)))
        );

        panel_base.add(panel_quiz, "card5");

        panel_individualScreen.setBackground(new java.awt.Color(212, 189, 163));

        button_backToMain2.setBackground(new java.awt.Color(31, 98, 143));
        button_backToMain2.setFont(new java.awt.Font("Cochin", 1, 14)); // NOI18N
        button_backToMain2.setForeground(new java.awt.Color(255, 255, 255));
        button_backToMain2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BackArrow.png"))); // NOI18N
        button_backToMain2.setText("Back to Main Screen");
        button_backToMain2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_backToMain2ActionPerformed(evt);
            }
        });

        panel_individualDeets.setBackground(new java.awt.Color(31, 98, 143));
        panel_individualDeets.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 65, 109), 2));

        panel_individualImage.setBackground(new java.awt.Color(204, 204, 204));
        panel_individualImage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));

        javax.swing.GroupLayout panel_individualImageLayout = new javax.swing.GroupLayout(panel_individualImage);
        panel_individualImage.setLayout(panel_individualImageLayout);
        panel_individualImageLayout.setHorizontalGroup(
            panel_individualImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 407, Short.MAX_VALUE)
        );
        panel_individualImageLayout.setVerticalGroup(
            panel_individualImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 477, Short.MAX_VALUE)
        );

        comboBox_shareOptions.setBackground(new java.awt.Color(250, 203, 132));
        comboBox_shareOptions.setFont(new java.awt.Font("Cochin", 0, 18)); // NOI18N
        comboBox_shareOptions.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Share", "Email", "Save to Desktop" }));
        comboBox_shareOptions.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(252, 179, 39), 2));
        comboBox_shareOptions.setOpaque(true);
        comboBox_shareOptions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBox_shareOptionsActionPerformed(evt);
            }
        });

        panel_pieceDeets.setBackground(new java.awt.Color(31, 98, 143));

        label_Title.setBackground(new java.awt.Color(31, 98, 143));
        label_Title.setFont(new java.awt.Font("Cochin", 3, 16)); // NOI18N
        label_Title.setForeground(new java.awt.Color(255, 255, 255));
        label_Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_Title.setText("Title");
        label_Title.setOpaque(true);

        label_Date.setBackground(new java.awt.Color(31, 98, 143));
        label_Date.setFont(new java.awt.Font("Cochin", 1, 16)); // NOI18N
        label_Date.setForeground(new java.awt.Color(255, 255, 255));
        label_Date.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_Date.setText("Created: ");
        label_Date.setOpaque(true);

        label_Artist.setBackground(new java.awt.Color(31, 98, 143));
        label_Artist.setFont(new java.awt.Font("Cochin", 1, 16)); // NOI18N
        label_Artist.setForeground(new java.awt.Color(255, 255, 255));
        label_Artist.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_Artist.setText("Created By: ");
        label_Artist.setOpaque(true);

        label_Place.setBackground(new java.awt.Color(31, 98, 143));
        label_Place.setFont(new java.awt.Font("Cochin", 1, 16)); // NOI18N
        label_Place.setForeground(new java.awt.Color(255, 255, 255));
        label_Place.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_Place.setText("Made In: ");
        label_Place.setOpaque(true);

        textPane_description.setBackground(new java.awt.Color(31, 98, 143));
        textPane_description.setBorder(null);
        textPane_description.setFont(new java.awt.Font("Cochin", 1, 16)); // NOI18N
        textPane_description.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(textPane_description);

        javax.swing.GroupLayout panel_pieceDeetsLayout = new javax.swing.GroupLayout(panel_pieceDeets);
        panel_pieceDeets.setLayout(panel_pieceDeetsLayout);
        panel_pieceDeetsLayout.setHorizontalGroup(
            panel_pieceDeetsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_pieceDeetsLayout.createSequentialGroup()
                .addContainerGap(109, Short.MAX_VALUE)
                .addGroup(panel_pieceDeetsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_Place, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_Artist, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_Date, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_Title, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(71, 71, 71))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_pieceDeetsLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 707, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panel_pieceDeetsLayout.setVerticalGroup(
            panel_pieceDeetsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_pieceDeetsLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(label_Title, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(label_Date, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(label_Artist, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(label_Place, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout panel_individualDeetsLayout = new javax.swing.GroupLayout(panel_individualDeets);
        panel_individualDeets.setLayout(panel_individualDeetsLayout);
        panel_individualDeetsLayout.setHorizontalGroup(
            panel_individualDeetsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_individualDeetsLayout.createSequentialGroup()
                .addGroup(panel_individualDeetsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_individualDeetsLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(panel_individualImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_individualDeetsLayout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(comboBox_shareOptions, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addComponent(panel_pieceDeets, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );
        panel_individualDeetsLayout.setVerticalGroup(
            panel_individualDeetsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_individualDeetsLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(panel_individualDeetsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panel_pieceDeets, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel_individualDeetsLayout.createSequentialGroup()
                        .addComponent(panel_individualImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(comboBox_shareOptions, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panel_individualScreenLayout = new javax.swing.GroupLayout(panel_individualScreen);
        panel_individualScreen.setLayout(panel_individualScreenLayout);
        panel_individualScreenLayout.setHorizontalGroup(
            panel_individualScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_individualScreenLayout.createSequentialGroup()
                .addGroup(panel_individualScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_individualScreenLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(button_backToMain2))
                    .addGroup(panel_individualScreenLayout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(panel_individualDeets, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        panel_individualScreenLayout.setVerticalGroup(
            panel_individualScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_individualScreenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(button_backToMain2)
                .addGap(51, 51, 51)
                .addComponent(panel_individualDeets, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        panel_base.add(panel_individualScreen, "card6");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_base, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_base, javax.swing.GroupLayout.PREFERRED_SIZE, 766, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void changePanel(JPanel panelBase, JPanel panelAdd) {
        
        panelBase.removeAll();
        panelBase.add(panelAdd);
        panelBase.repaint();
        panelBase.revalidate();

    }
    
    private void maxBoxes() {
        
        if (checkBoxesFilled <= 5) {
            label_counter.setText("You have selected " + checkBoxesFilled + " out of 5 available options");
        }
        else {
            label_counter.setText("You've reached the max number of options! Please unselect.");
        }
    }
    
    private void chooseFilter(JCheckBox checkbox, String filter) {
        checkboxes.add(checkbox);
        if (checkbox.isSelected()) {
            checkBoxesFilled += 1;
            userSelection.addFilter(filter);
            
        }
        else if (!checkbox.isSelected()) {
            checkBoxesFilled -= 1;
        }
    }
    
    private void checkBox_ArchitectureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBox_ArchitectureActionPerformed
        
        chooseFilter(checkBox_Architecture, "architecture");
        maxBoxes();
        
    }//GEN-LAST:event_checkBox_ArchitectureActionPerformed

    private void checkBox_AncientGreeceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBox_AncientGreeceActionPerformed

        chooseFilter(checkBox_AncientGreece, "arts-of-greece-rome-and-byzantium");
        maxBoxes();
        
    }//GEN-LAST:event_checkBox_AncientGreeceActionPerformed

    private void checkBox_AmericasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBox_AmericasActionPerformed
        
        chooseFilter(checkBox_Americas, "arts-of-the-americas");
        maxBoxes();
        
    }//GEN-LAST:event_checkBox_AmericasActionPerformed

    private void checkBox_ModernismActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBox_ModernismActionPerformed

        chooseFilter(checkBox_Modernism, "modernism");
        maxBoxes();
        
    }//GEN-LAST:event_checkBox_ModernismActionPerformed

    private void checkBox_ImpressionismActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBox_ImpressionismActionPerformed

        chooseFilter(checkBox_Impressionism, "impressionism");
        maxBoxes();
        
    }//GEN-LAST:event_checkBox_ImpressionismActionPerformed

    private void checkBox_AsiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBox_AsiaActionPerformed

        chooseFilter(checkBox_Asia, "arts-of-asia");
        maxBoxes();
        
    }//GEN-LAST:event_checkBox_AsiaActionPerformed

    private void checkBox_AnimalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBox_AnimalsActionPerformed

        chooseFilter(checkBox_Animals, "animals");
        maxBoxes();
        
    }//GEN-LAST:event_checkBox_AnimalsActionPerformed

    private void checkBox_PopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBox_PopActionPerformed

        chooseFilter(checkBox_Pop, "pop");
        maxBoxes();
        
    }//GEN-LAST:event_checkBox_PopActionPerformed

    private void checkBox_PhotographyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBox_PhotographyActionPerformed

        chooseFilter(checkBox_Photography, "photography");
        maxBoxes();
        
    }//GEN-LAST:event_checkBox_PhotographyActionPerformed

    private void checkBox_AfricaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBox_AfricaActionPerformed

        chooseFilter(checkBox_Africa, "arts-of-africa");
        maxBoxes();
        
    }//GEN-LAST:event_checkBox_AfricaActionPerformed

    private void checkBox_LandscapesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBox_LandscapesActionPerformed

        chooseFilter(checkBox_Landscapes, "landscapes");
        maxBoxes();
        
    }//GEN-LAST:event_checkBox_LandscapesActionPerformed

    private void checkBox_MiniatureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBox_MiniatureActionPerformed

        chooseFilter(checkBox_Miniature, "miniature");
        maxBoxes();
        
    }//GEN-LAST:event_checkBox_MiniatureActionPerformed

    private void button_ProceedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_ProceedActionPerformed
        // TODO add your handling code here:
        
        if (checkBoxesFilled != 0 && checkBoxesFilled <= 5) {

            changePanel(panel_base, panel_mainScreen);
            
            TreeMap things = userSelection.getFilters();
            Collection values = things.values();
            ArrayList<String> value = new ArrayList<>(values);
            
            for (String filter : value) {
                System.out.println(filter);
            }
            
            dh.compileArtworks(userSelection);
            artworks = dh.getArtworkList();
            
            String artworkSize = Integer.toString(panel_ImageView1.getWidth()) + "," 
                    + Integer.toString(panel_ImageView1.getHeight());
            
            String individualSize = Integer.toString(panel_individualImage.getWidth()) + "," 
                    + Integer.toString(panel_individualImage.getHeight());
            
            ImageHandler ih;
            BufferedImage image;
            
            for (Artwork piece : artworks) {
                
                ih = new ImageHandler(piece);
                image = ih.getArtworkImage(artworkSize);
                BufferedImage mainImage = ih.getArtworkImage(individualSize);
                imagePanels.add(image); 
                individualPanels.add(mainImage);
                
                String label = piece.getTitle();
                if (label.length() >= 52) {
                    label = label.substring(0, 52) + "...";
                }
                imageLabels.add(label);
            }
            
            setup();
            
        }
    }//GEN-LAST:event_button_ProceedActionPerformed

    private void setup() {
        
            ((ImagePanel)panel_ImageView1).updateImage(imagePanels.get(4));
            ((ImagePanel)panel_ImageView2).updateImage(imagePanels.get(0));
            ((ImagePanel)panel_ImageView3).updateImage(imagePanels.get(1));
            
            
            label_LabelView1.setText(imageLabels.get(4));
            label_LabelView2.setText(imageLabels.get(0));
            label_LabelView3.setText(imageLabels.get(1));
            
            mainButtons.add(button_XImage1);
            mainButtons.add(button_XImage2);
            mainButtons.add(button_XImage3);
            mainButtons.add(button_MaxImage3);
            mainButtons.add(button_MaxImage1);
            mainButtons.add(button_MaxImage2);
            
            for (JButton button : mainButtons) {
                button.setOpaque(false);
                button.setContentAreaFilled(false);
                button.setBorderPainted(false);
            }

    }
    
    private void button_InstructionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_InstructionsActionPerformed
        // TODO add your handling code here:
        changePanel(panel_base, panel_Instructions);
    }//GEN-LAST:event_button_InstructionsActionPerformed

    private void button_backToMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_backToMainActionPerformed
        // TODO add your handling code here:
        changePanel(panel_base, panel_mainScreen);
    }//GEN-LAST:event_button_backToMainActionPerformed

    private void button_regenerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_regenerateActionPerformed
        // TODO add your handling code here:
        
        changePanel(panel_base, panel_welcome);
        
        resetInformation();

    }//GEN-LAST:event_button_regenerateActionPerformed

    private void resetInformation() {
        
        for (JCheckBox checkbox : checkboxes) {
            if (checkbox.isSelected()) {
                checkbox.setSelected(false);
            }
        }
        
        checkBoxesFilled = 0;
        label_counter.setText("You have selected " + checkBoxesFilled + " out of 5 available options");
        userSelection.clearFilters();
        artworks.clear();
        
        imagePanels.clear();
        imageLabels.clear();
        
    }
    private void button_backToMain1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_backToMain1ActionPerformed
        // TODO add your handling code here:
        changePanel(panel_base, panel_mainScreen);
    }//GEN-LAST:event_button_backToMain1ActionPerformed

    private void button_miniQuizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_miniQuizActionPerformed
        // TODO add your handling code here:
        
        changePanel(panel_base, panel_quiz);
        qe = new QuizEvaluator(artworks);
        
        ArrayList<String> questions1 = qe.question1();
        
        ArrayList<JRadioButton> options = new ArrayList<>();
        
        options.add(radioButton_answer1);
        options.add(radioButton_answer2);
        options.add(radioButton_answer3);
        options.add(radioButton_answer4);
        options.add(radioButton_answer5);
        
        String answer = qe.getAnswer1();
        int indexOfAnswer = qe.indexAnswer1();
        
        label_question1.setText("<html>" + label_question1.getText() + 
                " <i>" + (artworks.get(indexOfAnswer)).getTitle() + "</i>" + "?</html>");
        
        for (int i = 0; i < questions1.size(); i++) {
            
            (options.get(i)).setText(questions1.get(i));
        }

    }//GEN-LAST:event_button_miniQuizActionPerformed

    private void button_NextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_NextActionPerformed
        // TODO add your handling code here:
        countClicks += 1;
        
        photoCarousel(panel_ImageView1, panel_ImageView2, panel_ImageView3,
                label_LabelView1, label_LabelView2, label_LabelView3);
        
    }//GEN-LAST:event_button_NextActionPerformed

    private void button_BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_BackActionPerformed
        // TODO add your handling code here:
        countClicks -= 1;
        
        photoCarousel(panel_ImageView1, panel_ImageView2, panel_ImageView3,
                label_LabelView1, label_LabelView2, label_LabelView3);
    }//GEN-LAST:event_button_BackActionPerformed

    private void photoCarousel(JPanel panel1, JPanel panel2, JPanel panel3, 
            JLabel label1, JLabel label2, JLabel label3) {
        
        if (countClicks > imagePanels.size() - 1) {
            countClicks = 0;
        }
        if (countClicks < 0) {
            countClicks = imagePanels.size() - 1;
        }
        
        int beforeCount = countClicks - 1;
        if (beforeCount < 0) {
            beforeCount = imagePanels.size() - 1;
        }
        
        int afterCount = countClicks + 1;
        if (afterCount >= imagePanels.size()) {
            afterCount = 0;
        }
        
        ((ImagePanel)panel1).updateImage(imagePanels.get(beforeCount));
        ((ImagePanel)panel2).updateImage(imagePanels.get(countClicks));
        ((ImagePanel)panel3).updateImage(imagePanels.get(afterCount));
        
        label1.setText(imageLabels.get(beforeCount));
        label2.setText(imageLabels.get(countClicks));
        label3.setText(imageLabels.get(afterCount));  
    }
    
    private void radioButton_answer2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButton_answer2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioButton_answer2ActionPerformed

    private void button_backToMain2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_backToMain2ActionPerformed
        // TODO add your handling code here:
        changePanel(panel_base, panel_mainScreen);
    }//GEN-LAST:event_button_backToMain2ActionPerformed

    private void button_MaxImage1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_MaxImage1ActionPerformed
        // TODO add your handling code here:
        changePanel(panel_base, panel_individualScreen);
        int index = imagePanels.indexOf(((ImagePanel)panel_ImageView1).getImage());
        setIndividualScreen(index);
    }//GEN-LAST:event_button_MaxImage1ActionPerformed

    private void setIndividualScreen(int index) {
        BufferedImage currentImage = individualPanels.get(index);
        ((ImagePanel)panel_individualImage).updateImage(currentImage);
        
        Artwork individualPiece = artworks.get(index);
        label_Title.setText(individualPiece.getTitle());
        label_Date.setText("Created: " + individualPiece.getDate_created());
        label_Artist.setText("Created By: " + individualPiece.getArtist());
        label_Place.setText("Made In: " + individualPiece.getPlace_created());
        
        String description = individualPiece.getShort_description();
        textPane_description.setText(description);
        textPane_description.setContentType("text/html");
        textPane_description.setText(
        "<html>" +
            "<div style='text-align: center; line-height: 1.6;'>" +
            description +
            "</div>" +
        "</html>");
    }
    
    private void comboBox_shareOptionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBox_shareOptionsActionPerformed
        // TODO add your handling code here:
        String optionSelected = (comboBox_shareOptions.getSelectedItem()).toString();
        System.out.println(optionSelected);
        BufferedImage image = ((ImagePanel)panel_individualImage).getImage();
        
        if (optionSelected.equals("Save to Desktop")) {
            
            JFileChooser jfc = new JFileChooser();
            
            if (jfc.showSaveDialog(this) == jfc.APPROVE_OPTION) {
                
                try {
                    File outputFile = jfc.getSelectedFile();
                    String path = outputFile.getAbsolutePath();
                    if (!(path.toLowerCase()).endsWith(".png")) {
                        outputFile = new File(path + ".png");
                    }
                    ImageIO.write(image, "png", outputFile);
                } catch (IOException ex) {
                    Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_comboBox_shareOptionsActionPerformed

    private void button_MaxImage2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_MaxImage2ActionPerformed
        // TODO add your handling code here:
        changePanel(panel_base, panel_individualScreen);
        int index = imagePanels.indexOf(((ImagePanel)panel_ImageView2).getImage());
        setIndividualScreen(index);
    }//GEN-LAST:event_button_MaxImage2ActionPerformed

    private void button_MaxImage3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_MaxImage3ActionPerformed
        // TODO add your handling code here:
        changePanel(panel_base, panel_individualScreen);
        int index = imagePanels.indexOf(((ImagePanel)panel_ImageView3).getImage());
        setIndividualScreen(index);
    }//GEN-LAST:event_button_MaxImage3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_Back;
    private javax.swing.JButton button_Instructions;
    private javax.swing.JButton button_MaxImage1;
    private javax.swing.JButton button_MaxImage2;
    private javax.swing.JButton button_MaxImage3;
    private javax.swing.JButton button_Next;
    private javax.swing.JButton button_Proceed;
    private javax.swing.JButton button_XImage1;
    private javax.swing.JButton button_XImage2;
    private javax.swing.JButton button_XImage3;
    private javax.swing.JButton button_backToMain;
    private javax.swing.JButton button_backToMain1;
    private javax.swing.JButton button_backToMain2;
    private javax.swing.JButton button_miniQuiz;
    private javax.swing.JButton button_regenerate;
    private javax.swing.JCheckBox checkBox_Africa;
    private javax.swing.JCheckBox checkBox_Americas;
    private javax.swing.JCheckBox checkBox_AncientGreece;
    private javax.swing.JCheckBox checkBox_Animals;
    private javax.swing.JCheckBox checkBox_Architecture;
    private javax.swing.JCheckBox checkBox_Asia;
    private javax.swing.JCheckBox checkBox_Impressionism;
    private javax.swing.JCheckBox checkBox_Landscapes;
    private javax.swing.JCheckBox checkBox_Miniature;
    private javax.swing.JCheckBox checkBox_Modernism;
    private javax.swing.JCheckBox checkBox_Photography;
    private javax.swing.JCheckBox checkBox_Pop;
    private javax.swing.JComboBox<String> comboBox_shareOptions;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel label_Africa;
    private javax.swing.JLabel label_Americas;
    private javax.swing.JLabel label_AncientGreece;
    private javax.swing.JLabel label_Animals;
    private javax.swing.JLabel label_Architecture;
    private javax.swing.JLabel label_Artist;
    private javax.swing.JLabel label_Asia;
    private javax.swing.JLabel label_Date;
    private javax.swing.JLabel label_Impressionism;
    private javax.swing.JLabel label_Instructions;
    private javax.swing.JLabel label_LabelView1;
    private javax.swing.JLabel label_LabelView2;
    private javax.swing.JLabel label_LabelView3;
    private javax.swing.JLabel label_Landscapes;
    private javax.swing.JLabel label_MainScreen;
    private javax.swing.JLabel label_MiniQuiz;
    private javax.swing.JLabel label_Miniature;
    private javax.swing.JLabel label_Modernism;
    private javax.swing.JLabel label_Photography;
    private javax.swing.JLabel label_Place;
    private javax.swing.JLabel label_Pop;
    private javax.swing.JLabel label_Title;
    private javax.swing.JLabel label_Welcome;
    private javax.swing.JLabel label_counter;
    private javax.swing.JLabel label_question1;
    private javax.swing.JLabel label_question2;
    private javax.swing.JPanel panel_ImageView1;
    private javax.swing.JPanel panel_ImageView2;
    private javax.swing.JPanel panel_ImageView3;
    private javax.swing.JPanel panel_Images;
    private javax.swing.JPanel panel_Instructions;
    private javax.swing.JPanel panel_base;
    private javax.swing.JPanel panel_individualDeets;
    private javax.swing.JPanel panel_individualImage;
    private javax.swing.JPanel panel_individualScreen;
    private javax.swing.JPanel panel_mainScreen;
    private javax.swing.JPanel panel_options;
    private javax.swing.JPanel panel_pieceDeets;
    private javax.swing.JPanel panel_question1;
    private javax.swing.JPanel panel_question2;
    private javax.swing.JPanel panel_quiz;
    private javax.swing.JPanel panel_quizScreen;
    private javax.swing.JPanel panel_welcome;
    private javax.swing.JRadioButton radioButton_answer1;
    private javax.swing.JRadioButton radioButton_answer2;
    private javax.swing.JRadioButton radioButton_answer3;
    private javax.swing.JRadioButton radioButton_answer4;
    private javax.swing.JRadioButton radioButton_answer5;
    private javax.swing.JScrollPane scrollPane_instructions;
    private javax.swing.JTextArea textArea_instructions;
    private javax.swing.JTextPane textPane_description;
    // End of variables declaration//GEN-END:variables
}
